services:
  bot:
    build: .
    container_name: food_bot
    restart: always  # Если бот упадет или сервер перезагрузится — он встанет сам
    env_file:
      - .env         # Читаем пароли из файла .env
    volumes:
      - .:/app       # Связываем папку на сервере с папкой внутри (чтобы база сохранялась)